FROM amazon/dynamodb-local

USER root

COPY data/dynamodb/migration.db /home/dynamodblocal/data/shared-local-instance.db

EXPOSE 8000

CMD  ["-jar", "DynamoDBLocal.jar", "-cors", "http://localhost:8080" ,"-sharedDb","-dbPath", "/home/dynamodblocal/data"]
