version: '3.9'
services:
  frontend:
    build:
      context: .
      target: 'develop-stage'
    container_name: 'blazar-frontend'
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb
    command: /bin/sh -c "quasar dev -m spa --bundler=webpack"

  dynamodb:
    build:
      context: .
      dockerfile: Dockerfile.dynamodb
    container_name: dynamodb
    hostname: dynamodb
    restart: always
    ports:
      - "8000:8000"

  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
    depends_on:
      - dynamodb
